// Authentication API
@AuthAPI_HostAddress = http://localhost:5184/api/Authenticate

// Register User API
POST {{AuthAPI_HostAddress}}/register
Content-Type: application/json

{
  "username": "nack",
  "email": "nack@email.com",
  "password": "Wow@55555"
}

###

// Register Admin API
POST {{AuthAPI_HostAddress}}/register-admin
Content-Type: application/json

{
  "username": "admin1",
  "email": "admin1@email.com",
  "password": "Admin@1234"
}

###

// Login
POST {{AuthAPI_HostAddress}}/login
Content-Type: application/json

{
  "username": "nack",
  "password": "Wow@55555"
}